mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
log4j:
    rootLogger: info, stdout
    appender:
         stdout: org.apache.log4j.ConsoleAppender
spring:
    batch:
       job:
         enabled: false
    main:
      allow:
        bean-definition-overriding: true
server:
  port: 8083
management:
  port: 8083
  security:
    enabled: false  #




